#ifndef CONFIG_H
#define CONFIG_H

// waardes ingesteld via make menuconfig

#define BS_WIFI_MODE_AP		CONFIG_ESP_WIFI_MODE_AP //TRUE:AP FALSE:STA
#define BS_WIFI_SSID		CONFIG_ESP_WIFI_SSID
#define BS_WIFI_PASS		CONFIG_ESP_WIFI_PASSWORD
#define BS_MAX_STA_CONN		CONFIG_MAX_STA_CONN

#define TAG CONFIG_TAG

#endif